### ISSUE TITLE
请问ERROR401是啥？

### ISSUE THREAD

**Issue by TAOTAO6666666** [easychen/deepgpt-dist#3]
请问ERROR401是啥？

**Comment by wangfeng35** [comment]
同问

**Comment by easychen** [comment]
![image](https://github.com/easychen/deepgpt-dist/assets/1294760/3f774b12-7a83-481a-8283-31063026f46f)

如果要用 openai的key，需要手动修改 api 地址为 https://api.openai.com ，切保证浏览器网络可以访问这个地址

**Comment by trampboy** [comment]
@easychen 感谢，已可以使用
